### ISSUE TITLE
Video tutoriales de semilla

### ISSUE THREAD

**Issue by aVolpe** [InstIDEA/controlciudadano#100]
Creación de video tutoriales de cómo usar los datos importados para su análisis y del panel de verificación

# Development notes

Los videos se deben preparar en un issue paralelo a este.

# Definition of donde

* [x] [Portal] Página creada `/ddjj/tutorial`
* [x] [Portal] Página muestra todos los videos, un video tiene `titulo`, `descripción` (html) y `link` (a youtube)
* [x] [API] Tabla `analysis.tutorials` creada con las columnas `id`, `titulo`, `description`, `link`, `type` (para utilizar para otro tipo de tutoriales, debe tener valor 'semillas')
* [x] [API] Redash que retorne todas las filas de la tabla `analysis.tutorials`.
* [x] [Portal] Agregar a RedashAPI el nuevo servicio.

**Comment by sdakef** [comment]
![2020 12 30 Diseño pantalla videos tutoriales Control Ciudadano](https://user-images.githubusercontent.com/12274935/103354835-61674700-4a8b-11eb-96f9-d142c26edecf.jpg)

**Comment by sdakef** [comment]
![2020 12 30 Diseño pantalla videos tutoriales Control Ciudadano (1)](https://user-images.githubusercontent.com/12274935/103354970-c327b100-4a8b-11eb-8cd1-e3498289ec36.jpg)
