### ISSUE TITLE
Revisar personas con nombre "VACANTE VACANTE"

### ISSUE THREAD

**Issue by yolile** [InstIDEA/controlciudadano#117]
![image](https://user-images.githubusercontent.com/6834122/101765939-cea53f00-3ac0-11eb-9c6d-63a792fd8612.png)

# Definition of done

* [ ] Fuente del `VACANTE VACANTE` definida
* [ ] Bajar prioridad de la fuente
* [ ] Modificar ETL para no incluir estos datos

**Comment by aVolpe** [comment]
Todos los datos provienen de la SFP, y puede o no que sean cargos ofuscados.
