### ISSUE TITLE
[Semillas] Panel de verificación en homepage

### ISSUE THREAD

**Issue by aVolpe** [InstIDEA/controlciudadano#128]
Se debe agregar un link a la página de "Verificación de DDJJ faltantes" (#99)

# Definition of done

* [x] Link para ir a `/ddjj` desde página de inicio
* [x] Link para ir a `/ddjj` desde página de inicio (versión responsive)
* [x] No scrollear para acceder desde página de inicio

# Developer notes
* Swap the options cards with the statistics cards to prevent scroll

**Comment by aVolpe** [comment]
Solicitar a Celia rediseño.

**Comment by aguilerapy** [comment]
![imagen](https://user-images.githubusercontent.com/48607824/103037575-eb268a00-454a-11eb-9b91-b5b35f8e8596.png)
