### ISSUE TITLE
Contralory DAC no longer compatible with new contralory page

### ISSUE THREAD

**Issue by Luxter77** [InstIDEA/controlciudadano#179]
The old page from where we got the PDFs (https://djbpublico.contraloria.gov.py/) no longer exists, so we can't get any more affidavits from there

**Comment by aVolpe** [comment]
The new portal is here: https://portaldjbr.contraloria.gov.py/portal-djbr/

**Comment by aVolpe** [comment]
There are about 800k declarations now (up from 12k in the old portal), so we need a new strategy to fetch all.

We can:

1. Create a dag, called `contralory-declaration-link-fetcher` that iterate the list and fetches the link to the pdf
2. Create a dag called `contralory-declaration-downloader` that iterate the result of the other dag and downloads the pdfs.

For the dag1:
* It should store the full list in a table (`staging.contralory_links_to_download`).
* Portal require a search term to return data, so we can send a vowel (fist a, then b, and so on), and iterate the paginated result.
* It should handle retries and networks issues (rate limiters)

The dag 2:

* Should fetch a bunch of not downloaded declarations and download them
* Should not fetch the full list (maybe use a variable for the batch size)
* It should work in many threads.

**Comment by aVolpe** [comment]
The name also appear to be a valid name, we can store that name in the staging table.

**Comment by aVolpe** [comment]
Both dags where implemented in #181  and #182  can you review them and close this issue?
