### ISSUE TITLE
Modificar títulos y descripciones de action

### ISSUE THREAD

**Issue by yolile** [InstIDEA/controlciudadano#29]
Editar títulos y descripciones según [documento](https://docs.google.com/document/d/1i7CPWZvizhwbs3FGDTxvJPlwwcj5tc3OMyjSKEfocNQ/)

**Comment by nativaldezt** [comment]
En realidad solo falta el título y su descripción, el resto ya se hizo en https://github.com/InstIDEA/controlciudadano/commit/414603eeaee78438b00459c22d5f550a58207343#diff-d4a8302e95ab57fd8ea38010bf25f7ba6f771d98817c2d81f28ec82aca4f9b75
