### ISSUE TITLE
Filtro de misma dirección no se entiende que se puede clickear

### ISSUE THREAD

**Issue by nativaldezt** [InstIDEA/controlciudadano#64]
Agergar check y cambiar el cursor para indicar que se puede clickear

![image](https://user-images.githubusercontent.com/72802235/100277438-e964a900-2f41-11eb-9f82-8c6aeffaae56.png)

**Comment by aVolpe** [comment]
El checkbox no queda muy bien, se modifico para que el cursor cambie cuando se mueve encima del timeline.

**Comment by aVolpe** [comment]
fixed in #78
