### ISSUE TITLE
ETL Declaraciones juradas

### ISSUE THREAD

**Issue by aVolpe** [InstIDEA/controlciudadano#94]
Desarrollar un proceso que permita actualizar automáticamente, de forma periódica, las nuevas declaraciones juradas disponibles en https://djbpublico.contraloria.gov.py/. Desarrollo de funcionalidades de búsqueda y descarga de datos con los datos importados

**Comment by Luxter77** [comment]
Para que esto funcione ahora mismo necesitamos:
- [] Convertir el sistema que ya está en un DAC de Apache Airflow.
- [] Una vez descargados crear un servicio que recorra los PDF y extraiga: nombre, año y versión.
- [] Crear un servicio que Recorra los PDF una vez cargados y chequee cuales necesitan ser arreglados (alineación, arreglar exposición y arreglar contraste) antes de poder extraer la información a través de OCR.
- [] Crear un servicio que realice OCR en los PDF arreglados y mande esa información a las tablas en el DB

**Comment by Luxter77** [comment]
Para extraer la información de los PDF hay que tener en cuenta que:
1. Los PDF hechos a mano (normalmente los que son menoes a 2015), con estos no podemos hacer mucho, por ahora, solo extraer información del nombre del archivo y stashear
2. Los PDF con texto, Ya se pueden extraer con los scripts existentes
3. Los PDF bien escaneados deben ser "sandwicheados" antes de pasar por el script que extrae datos

**Comment by aVolpe** [comment]
Duplicado de #91
